FROM ubuntu:focal

EXPOSE 5000

ENV ASPNETCORE_ENVIRONMENT="Production"
ENV ASPNETCORE_URLS="http://*:5000"

RUN \
  apt-get -y update && \
  apt-get -y install \
  apt-utils \
  wget \
  apt-transport-https \
  unzip \
  acl \
  libssl1.0

RUN \
  wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb && \
  dpkg -i packages-microsoft-prod.deb && \
  apt-get -y update && \
  apt-get -y install aspnetcore-runtime-5.0

RUN \
  mkdir -p /var/www/uremote && \
  mkdir /config && \
  wget -q https://github.com/lucent-sea/URemote/releases/latest/download/URemote_Server_Linux-x64.zip && \
  unzip -o URemote_Server_Linux-x64.zip -d /var/www/uremote && \
  rm URemote_Server_Linux-x64.zip

RUN \
  mkdir -p /uremote-data && \
  sed -i 's/DataSource=URemote.db/DataSource=\/uremote-data\/URemote.db/' /var/www/uremote/appsettings.json

VOLUME "/uremote-data"

WORKDIR /var/www/uremote

COPY DockerMain.sh /

RUN chmod 755 /DockerMain.sh

ENTRYPOINT ["/DockerMain.sh"]